version: '3.8'

services:

  web:
    build: .
    container_name: ci4_web
    ports:
      - "8080:80"        # aplikasi bisa dibuka lewat http://localhost:8080
    volumes:
      - .:/var/www/html  # sinkron direktori project
    depends_on:
      - db
      - minio            # supaya MinIO juga aktif

  db:
    image: mariadb:10.5
    container_name: ci4_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_mahasiswa
      MYSQL_USER: ci4
      MYSQL_PASSWORD: ci4pass
    ports:
      - "3307:3306"
    volumes:
      - mariadbdata:/var/lib/mysql

  minio:
    image: minio/minio
    container_name: penyimpanan_minio
    restart: always
    ports:
      - "9000:9000"      # port API
      - "9001:9001"      # port dashboard
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: miniosandi
    command: server /data --console-address ":9001"
    volumes:
      - penyimpanandata:/data

volumes:
  mariadbdata:
  penyimpanandata:
